name: cv_ml_assignment
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - numpy
  - pandas
  - matplotlib
  - opencv
  - scikit-learn
  - tensorflow
  - keras
  - pillow
  - pip
  - pip:
      - torch
      - torchvision
      - yolov5
