import numpy as np
rg = np.random.default_rng()
arr = rg.normal(50,5,size = 1000)
print(arr)
print(arr.mean())
arr_  = np.sort(arr)
print((arr_[499]+arr_[500])/2)
print(arr_.std())
print((arr_.std())*(arr_.std()))
print(np. percentile(arr_, 25))
print(np. percentile(arr_, 75))